name: deploy-to-hf-spaces
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-api-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git lfs install
      - name: Push repo to API Space (Docker)
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          API_SPACE: ${{ secrets.API_SPACE }}
        run: |
          set -e
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          rm -rf api_space
          git clone https://huggingface.co/spaces/${HF_USERNAME}/${API_SPACE} api_space
          rsync -av --delete --exclude '.git' ./ api_space/
          cd api_space
          git add -A
          if git diff --cached --quiet; then
            echo "No changes for API Space."
          else
            git commit -m "Auto-deploy API from $GITHUB_SHA"
            git push https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${API_SPACE} HEAD:main
          fi

  deploy-ui-space:
    needs: deploy-api-space
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare UI bundle (Streamlit)
        run: |
          mkdir -p ui_bundle/ui
          cp -v ui/streamlit_app.py ui_bundle/ui/streamlit_app.py
          cat > ui_bundle/requirements.txt <<'EOF'
          streamlit==1.37.1
          requests==2.32.3
          EOF
          cat > ui_bundle/README.md <<'EOF'
          ---
          title: llm-nlp-ui
          sdk: streamlit
          app_file: ui/streamlit_app.py
          ---
          EOF
      - name: Push UI bundle to UI Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          UI_SPACE: ${{ secrets.UI_SPACE }}
        run: |
          set -e
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          rm -rf ui_space
          git clone https://huggingface.co/spaces/${HF_USERNAME}/${UI_SPACE} ui_space
          rsync -av --delete --exclude '.git' ui_bundle/ ui_space/
          cd ui_space
          git add -A
          if git diff --cached --quiet; then
            echo "No changes for UI Space."
          else
            git commit -m "Auto-deploy UI from $GITHUB_SHA"
            git push https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${UI_SPACE} HEAD:main
          fi
